# Generated by Django 5.2.1 on 2025-05-28 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_product_suppliers_category_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='suppliers',
            field=models.ManyToManyField(related_name='product_suppliers', to='core.supplier', verbose_name='Поставщики'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='products',
            field=models.ManyToManyField(related_name='supplier_products', through='core.SupplierProduct', to='core.product', verbose_name='Поставляемые товары'),
        ),
    ]
