# Generated by Django 5.2.1 on 2025-06-03 02:17

import apps.core.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_product_suppliers_alter_supplier_products'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promo',
            options={'verbose_name': 'Промокод', 'verbose_name_plural': 'Промокоды'},
        ),
        migrations.AlterModelOptions(
            name='promousage',
            options={'verbose_name': 'Использование промокода', 'verbose_name_plural': 'Использования промокодов'},
        ),
        migrations.RemoveField(
            model_name='order',
            name='client_timezone',
        ),
        migrations.RemoveField(
            model_name='promo',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='promo',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='promo',
            name='max_uses',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Максимальное количество использований'),
        ),
        migrations.AddField(
            model_name='promo',
            name='uses_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество использований'),
        ),
        migrations.AddField(
            model_name='promousage',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сумма скидки'),
        ),
        migrations.AddField(
            model_name='promousage',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.order', verbose_name='Заказ'),
        ),
        migrations.AlterField(
            model_name='order',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Скидка'),
        ),
        migrations.AlterField(
            model_name='order',
            name='promo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.promo', verbose_name='Промокод'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'В обработке'), ('confirmed', 'Подтвержден'), ('shipped', 'Отправлен'), ('delivered', 'Доставлен'), ('cancelled', 'Отменен')], default='pending', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='order',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Подытог'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Итого'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за единицу'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='product',
            name='suppliers',
            field=models.ManyToManyField(related_name='supplied_products', to='core.supplier', verbose_name='Поставщики'),
        ),
        migrations.AlterField(
            model_name='promo',
            name='code',
            field=models.CharField(max_length=20, unique=True, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='promo',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма скидки'),
        ),
        migrations.AlterField(
            model_name='promo',
            name='valid_from',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Действует с'),
        ),
        migrations.AlterField(
            model_name='promo',
            name='valid_until',
            field=models.DateTimeField(default=apps.core.models.get_default_valid_until, verbose_name='Действует до'),
        ),
        migrations.AlterField(
            model_name='promousage',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Покупатель'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to=settings.AUTH_USER_MODEL, verbose_name='Покупатель'),
        ),
        migrations.DeleteModel(
            name='ProductReview',
        ),
    ]
