# Generated by Django 5.2.1 on 2025-06-03 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_promo_options_alter_promousage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='client_timezone',
            field=models.CharField(default='Europe/Minsk', max_length=50, verbose_name='Часовой пояс клиента'),
        ),
    ]
