# Generated by Django 5.2.1 on 2025-06-03 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_order_client_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='contact_first_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Имя контактного лица'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='contact_last_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Фамилия контактного лица'),
        ),
    ]
