# Generated by Django 5.2.1 on 2025-06-03 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_employee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
