# Generated by Django 5.2.1 on 2025-06-03 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('content', '0003_remove_employee_position_employee_vacancy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='vacancy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_employees', to='content.vacancy', verbose_name='Вакансия'),
        ),
    ]
